app:
  jwt:
    secret: v9y$B&E)H@MbASDki(1EKDJa-NIPK!sd(Ka7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    accessToken:
      expiration:
        minutes: 30

    refreshToken:
      expiration:
        days: 7
  cors:
    allowed-origin-list: http://localhost:3000