spring:
  config:
    import:
      - app.yml

  profiles:
    active: local

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/discord?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: WjdWodnr#&33
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace