spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: wjdwodnr445@gmail.com
    password: xmlneispkvlvdgwh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 30 * 60 * 1000  # 30 * 60 * 1000 == 30분