spring:
  profiles:
    include:
      - db
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-request-size: 1GB
      max-file-size: 1GB

app:
  jwt:
    secret: v9y$B&E)H@MbASDki(1EKDJa-NIPK!sd(Ka7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
  cors:
    allowed-origin-list: http://localhost:3000
  url:
    server: http://localhost:8080

